// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtProto/sensor_msgs/Imu.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dtProto_2fsensor_5fmsgs_2fImu_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dtProto_2fsensor_5fmsgs_2fImu_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "dtProto/geometry_msgs/Vector.pb.h"
#include "dtProto/geometry_msgs/Orientation.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dtProto_2fsensor_5fmsgs_2fImu_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dtProto_2fsensor_5fmsgs_2fImu_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dtProto_2fsensor_5fmsgs_2fImu_2eproto;
namespace dtproto {
namespace sensor_msgs {
class Imu;
struct ImuDefaultTypeInternal;
extern ImuDefaultTypeInternal _Imu_default_instance_;
}  // namespace sensor_msgs
}  // namespace dtproto
PROTOBUF_NAMESPACE_OPEN
template<> ::dtproto::sensor_msgs::Imu* Arena::CreateMaybeMessage<::dtproto::sensor_msgs::Imu>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dtproto {
namespace sensor_msgs {

// ===================================================================

class Imu final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dtproto.sensor_msgs.Imu) */ {
 public:
  inline Imu() : Imu(nullptr) {}
  ~Imu() override;
  explicit PROTOBUF_CONSTEXPR Imu(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Imu(const Imu& from);
  Imu(Imu&& from) noexcept
    : Imu() {
    *this = ::std::move(from);
  }

  inline Imu& operator=(const Imu& from) {
    CopyFrom(from);
    return *this;
  }
  inline Imu& operator=(Imu&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Imu& default_instance() {
    return *internal_default_instance();
  }
  static inline const Imu* internal_default_instance() {
    return reinterpret_cast<const Imu*>(
               &_Imu_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Imu& a, Imu& b) {
    a.Swap(&b);
  }
  inline void Swap(Imu* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Imu* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Imu* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Imu>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Imu& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Imu& from) {
    Imu::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Imu* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dtproto.sensor_msgs.Imu";
  }
  protected:
  explicit Imu(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrientatonFieldNumber = 1,
    kAngularVelocityFieldNumber = 2,
    kLinearAccelerationFieldNumber = 3,
  };
  // .dtproto.geometry_msgs.Quaternion orientaton = 1;
  bool has_orientaton() const;
  private:
  bool _internal_has_orientaton() const;
  public:
  void clear_orientaton();
  const ::dtproto::geometry_msgs::Quaternion& orientaton() const;
  PROTOBUF_NODISCARD ::dtproto::geometry_msgs::Quaternion* release_orientaton();
  ::dtproto::geometry_msgs::Quaternion* mutable_orientaton();
  void set_allocated_orientaton(::dtproto::geometry_msgs::Quaternion* orientaton);
  private:
  const ::dtproto::geometry_msgs::Quaternion& _internal_orientaton() const;
  ::dtproto::geometry_msgs::Quaternion* _internal_mutable_orientaton();
  public:
  void unsafe_arena_set_allocated_orientaton(
      ::dtproto::geometry_msgs::Quaternion* orientaton);
  ::dtproto::geometry_msgs::Quaternion* unsafe_arena_release_orientaton();

  // .dtproto.geometry_msgs.Vector3d angular_velocity = 2;
  bool has_angular_velocity() const;
  private:
  bool _internal_has_angular_velocity() const;
  public:
  void clear_angular_velocity();
  const ::dtproto::geometry_msgs::Vector3d& angular_velocity() const;
  PROTOBUF_NODISCARD ::dtproto::geometry_msgs::Vector3d* release_angular_velocity();
  ::dtproto::geometry_msgs::Vector3d* mutable_angular_velocity();
  void set_allocated_angular_velocity(::dtproto::geometry_msgs::Vector3d* angular_velocity);
  private:
  const ::dtproto::geometry_msgs::Vector3d& _internal_angular_velocity() const;
  ::dtproto::geometry_msgs::Vector3d* _internal_mutable_angular_velocity();
  public:
  void unsafe_arena_set_allocated_angular_velocity(
      ::dtproto::geometry_msgs::Vector3d* angular_velocity);
  ::dtproto::geometry_msgs::Vector3d* unsafe_arena_release_angular_velocity();

  // .dtproto.geometry_msgs.Vector3d linear_acceleration = 3;
  bool has_linear_acceleration() const;
  private:
  bool _internal_has_linear_acceleration() const;
  public:
  void clear_linear_acceleration();
  const ::dtproto::geometry_msgs::Vector3d& linear_acceleration() const;
  PROTOBUF_NODISCARD ::dtproto::geometry_msgs::Vector3d* release_linear_acceleration();
  ::dtproto::geometry_msgs::Vector3d* mutable_linear_acceleration();
  void set_allocated_linear_acceleration(::dtproto::geometry_msgs::Vector3d* linear_acceleration);
  private:
  const ::dtproto::geometry_msgs::Vector3d& _internal_linear_acceleration() const;
  ::dtproto::geometry_msgs::Vector3d* _internal_mutable_linear_acceleration();
  public:
  void unsafe_arena_set_allocated_linear_acceleration(
      ::dtproto::geometry_msgs::Vector3d* linear_acceleration);
  ::dtproto::geometry_msgs::Vector3d* unsafe_arena_release_linear_acceleration();

  // @@protoc_insertion_point(class_scope:dtproto.sensor_msgs.Imu)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::dtproto::geometry_msgs::Quaternion* orientaton_;
    ::dtproto::geometry_msgs::Vector3d* angular_velocity_;
    ::dtproto::geometry_msgs::Vector3d* linear_acceleration_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dtProto_2fsensor_5fmsgs_2fImu_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Imu

// .dtproto.geometry_msgs.Quaternion orientaton = 1;
inline bool Imu::_internal_has_orientaton() const {
  return this != internal_default_instance() && _impl_.orientaton_ != nullptr;
}
inline bool Imu::has_orientaton() const {
  return _internal_has_orientaton();
}
inline const ::dtproto::geometry_msgs::Quaternion& Imu::_internal_orientaton() const {
  const ::dtproto::geometry_msgs::Quaternion* p = _impl_.orientaton_;
  return p != nullptr ? *p : reinterpret_cast<const ::dtproto::geometry_msgs::Quaternion&>(
      ::dtproto::geometry_msgs::_Quaternion_default_instance_);
}
inline const ::dtproto::geometry_msgs::Quaternion& Imu::orientaton() const {
  // @@protoc_insertion_point(field_get:dtproto.sensor_msgs.Imu.orientaton)
  return _internal_orientaton();
}
inline void Imu::unsafe_arena_set_allocated_orientaton(
    ::dtproto::geometry_msgs::Quaternion* orientaton) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.orientaton_);
  }
  _impl_.orientaton_ = orientaton;
  if (orientaton) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dtproto.sensor_msgs.Imu.orientaton)
}
inline ::dtproto::geometry_msgs::Quaternion* Imu::release_orientaton() {
  
  ::dtproto::geometry_msgs::Quaternion* temp = _impl_.orientaton_;
  _impl_.orientaton_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dtproto::geometry_msgs::Quaternion* Imu::unsafe_arena_release_orientaton() {
  // @@protoc_insertion_point(field_release:dtproto.sensor_msgs.Imu.orientaton)
  
  ::dtproto::geometry_msgs::Quaternion* temp = _impl_.orientaton_;
  _impl_.orientaton_ = nullptr;
  return temp;
}
inline ::dtproto::geometry_msgs::Quaternion* Imu::_internal_mutable_orientaton() {
  
  if (_impl_.orientaton_ == nullptr) {
    auto* p = CreateMaybeMessage<::dtproto::geometry_msgs::Quaternion>(GetArenaForAllocation());
    _impl_.orientaton_ = p;
  }
  return _impl_.orientaton_;
}
inline ::dtproto::geometry_msgs::Quaternion* Imu::mutable_orientaton() {
  ::dtproto::geometry_msgs::Quaternion* _msg = _internal_mutable_orientaton();
  // @@protoc_insertion_point(field_mutable:dtproto.sensor_msgs.Imu.orientaton)
  return _msg;
}
inline void Imu::set_allocated_orientaton(::dtproto::geometry_msgs::Quaternion* orientaton) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.orientaton_);
  }
  if (orientaton) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(orientaton));
    if (message_arena != submessage_arena) {
      orientaton = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, orientaton, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.orientaton_ = orientaton;
  // @@protoc_insertion_point(field_set_allocated:dtproto.sensor_msgs.Imu.orientaton)
}

// .dtproto.geometry_msgs.Vector3d angular_velocity = 2;
inline bool Imu::_internal_has_angular_velocity() const {
  return this != internal_default_instance() && _impl_.angular_velocity_ != nullptr;
}
inline bool Imu::has_angular_velocity() const {
  return _internal_has_angular_velocity();
}
inline const ::dtproto::geometry_msgs::Vector3d& Imu::_internal_angular_velocity() const {
  const ::dtproto::geometry_msgs::Vector3d* p = _impl_.angular_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::dtproto::geometry_msgs::Vector3d&>(
      ::dtproto::geometry_msgs::_Vector3d_default_instance_);
}
inline const ::dtproto::geometry_msgs::Vector3d& Imu::angular_velocity() const {
  // @@protoc_insertion_point(field_get:dtproto.sensor_msgs.Imu.angular_velocity)
  return _internal_angular_velocity();
}
inline void Imu::unsafe_arena_set_allocated_angular_velocity(
    ::dtproto::geometry_msgs::Vector3d* angular_velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.angular_velocity_);
  }
  _impl_.angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dtproto.sensor_msgs.Imu.angular_velocity)
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::release_angular_velocity() {
  
  ::dtproto::geometry_msgs::Vector3d* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::unsafe_arena_release_angular_velocity() {
  // @@protoc_insertion_point(field_release:dtproto.sensor_msgs.Imu.angular_velocity)
  
  ::dtproto::geometry_msgs::Vector3d* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  return temp;
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::_internal_mutable_angular_velocity() {
  
  if (_impl_.angular_velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::dtproto::geometry_msgs::Vector3d>(GetArenaForAllocation());
    _impl_.angular_velocity_ = p;
  }
  return _impl_.angular_velocity_;
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::mutable_angular_velocity() {
  ::dtproto::geometry_msgs::Vector3d* _msg = _internal_mutable_angular_velocity();
  // @@protoc_insertion_point(field_mutable:dtproto.sensor_msgs.Imu.angular_velocity)
  return _msg;
}
inline void Imu::set_allocated_angular_velocity(::dtproto::geometry_msgs::Vector3d* angular_velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.angular_velocity_);
  }
  if (angular_velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity));
    if (message_arena != submessage_arena) {
      angular_velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, angular_velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.angular_velocity_ = angular_velocity;
  // @@protoc_insertion_point(field_set_allocated:dtproto.sensor_msgs.Imu.angular_velocity)
}

// .dtproto.geometry_msgs.Vector3d linear_acceleration = 3;
inline bool Imu::_internal_has_linear_acceleration() const {
  return this != internal_default_instance() && _impl_.linear_acceleration_ != nullptr;
}
inline bool Imu::has_linear_acceleration() const {
  return _internal_has_linear_acceleration();
}
inline const ::dtproto::geometry_msgs::Vector3d& Imu::_internal_linear_acceleration() const {
  const ::dtproto::geometry_msgs::Vector3d* p = _impl_.linear_acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::dtproto::geometry_msgs::Vector3d&>(
      ::dtproto::geometry_msgs::_Vector3d_default_instance_);
}
inline const ::dtproto::geometry_msgs::Vector3d& Imu::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:dtproto.sensor_msgs.Imu.linear_acceleration)
  return _internal_linear_acceleration();
}
inline void Imu::unsafe_arena_set_allocated_linear_acceleration(
    ::dtproto::geometry_msgs::Vector3d* linear_acceleration) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.linear_acceleration_);
  }
  _impl_.linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dtproto.sensor_msgs.Imu.linear_acceleration)
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::release_linear_acceleration() {
  
  ::dtproto::geometry_msgs::Vector3d* temp = _impl_.linear_acceleration_;
  _impl_.linear_acceleration_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::unsafe_arena_release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:dtproto.sensor_msgs.Imu.linear_acceleration)
  
  ::dtproto::geometry_msgs::Vector3d* temp = _impl_.linear_acceleration_;
  _impl_.linear_acceleration_ = nullptr;
  return temp;
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::_internal_mutable_linear_acceleration() {
  
  if (_impl_.linear_acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::dtproto::geometry_msgs::Vector3d>(GetArenaForAllocation());
    _impl_.linear_acceleration_ = p;
  }
  return _impl_.linear_acceleration_;
}
inline ::dtproto::geometry_msgs::Vector3d* Imu::mutable_linear_acceleration() {
  ::dtproto::geometry_msgs::Vector3d* _msg = _internal_mutable_linear_acceleration();
  // @@protoc_insertion_point(field_mutable:dtproto.sensor_msgs.Imu.linear_acceleration)
  return _msg;
}
inline void Imu::set_allocated_linear_acceleration(::dtproto::geometry_msgs::Vector3d* linear_acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.linear_acceleration_);
  }
  if (linear_acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration));
    if (message_arena != submessage_arena) {
      linear_acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_acceleration, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.linear_acceleration_ = linear_acceleration;
  // @@protoc_insertion_point(field_set_allocated:dtproto.sensor_msgs.Imu.linear_acceleration)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace sensor_msgs
}  // namespace dtproto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dtProto_2fsensor_5fmsgs_2fImu_2eproto
