// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtProto/sensor_msgs/Joy.proto

#include "dtProto/sensor_msgs/Joy.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dtproto {
namespace sensor_msgs {
PROTOBUF_CONSTEXPR Joy::Joy(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.axes_)*/{}
  , /*decltype(_impl_.buttons_)*/{}
  , /*decltype(_impl_._buttons_cached_byte_size_)*/{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct JoyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JoyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~JoyDefaultTypeInternal() {}
  union {
    Joy _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JoyDefaultTypeInternal _Joy_default_instance_;
}  // namespace sensor_msgs
}  // namespace dtproto
static ::_pb::Metadata file_level_metadata_dtProto_2fsensor_5fmsgs_2fJoy_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_dtProto_2fsensor_5fmsgs_2fJoy_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dtProto_2fsensor_5fmsgs_2fJoy_2eproto = nullptr;

const uint32_t TableStruct_dtProto_2fsensor_5fmsgs_2fJoy_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dtproto::sensor_msgs::Joy, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dtproto::sensor_msgs::Joy, _impl_.axes_),
  PROTOBUF_FIELD_OFFSET(::dtproto::sensor_msgs::Joy, _impl_.buttons_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::dtproto::sensor_msgs::Joy)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dtproto::sensor_msgs::_Joy_default_instance_._instance,
};

const char descriptor_table_protodef_dtProto_2fsensor_5fmsgs_2fJoy_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035dtProto/sensor_msgs/Joy.proto\022\023dtproto"
  ".sensor_msgs\"$\n\003Joy\022\014\n\004axes\030\001 \003(\002\022\017\n\007but"
  "tons\030\002 \003(\005b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto = {
    false, false, 98, descriptor_table_protodef_dtProto_2fsensor_5fmsgs_2fJoy_2eproto,
    "dtProto/sensor_msgs/Joy.proto",
    &descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_dtProto_2fsensor_5fmsgs_2fJoy_2eproto::offsets,
    file_level_metadata_dtProto_2fsensor_5fmsgs_2fJoy_2eproto, file_level_enum_descriptors_dtProto_2fsensor_5fmsgs_2fJoy_2eproto,
    file_level_service_descriptors_dtProto_2fsensor_5fmsgs_2fJoy_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto_getter() {
  return &descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dtProto_2fsensor_5fmsgs_2fJoy_2eproto(&descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto);
namespace dtproto {
namespace sensor_msgs {

// ===================================================================

class Joy::_Internal {
 public:
};

Joy::Joy(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dtproto.sensor_msgs.Joy)
}
Joy::Joy(const Joy& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Joy* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.axes_){from._impl_.axes_}
    , decltype(_impl_.buttons_){from._impl_.buttons_}
    , /*decltype(_impl_._buttons_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:dtproto.sensor_msgs.Joy)
}

inline void Joy::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.axes_){arena}
    , decltype(_impl_.buttons_){arena}
    , /*decltype(_impl_._buttons_cached_byte_size_)*/{0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Joy::~Joy() {
  // @@protoc_insertion_point(destructor:dtproto.sensor_msgs.Joy)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Joy::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.axes_.~RepeatedField();
  _impl_.buttons_.~RepeatedField();
}

void Joy::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Joy::Clear() {
// @@protoc_insertion_point(message_clear_start:dtproto.sensor_msgs.Joy)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.axes_.Clear();
  _impl_.buttons_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Joy::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated float axes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_axes(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 13) {
          _internal_add_axes(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // repeated int32 buttons = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_buttons(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_buttons(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Joy::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dtproto.sensor_msgs.Joy)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float axes = 1;
  if (this->_internal_axes_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_axes(), target);
  }

  // repeated int32 buttons = 2;
  {
    int byte_size = _impl_._buttons_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteInt32Packed(
          2, _internal_buttons(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dtproto.sensor_msgs.Joy)
  return target;
}

size_t Joy::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dtproto.sensor_msgs.Joy)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float axes = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_axes_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    total_size += data_size;
  }

  // repeated int32 buttons = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      Int32Size(this->_impl_.buttons_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._buttons_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Joy::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Joy::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Joy::GetClassData() const { return &_class_data_; }


void Joy::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Joy*>(&to_msg);
  auto& from = static_cast<const Joy&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dtproto.sensor_msgs.Joy)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.axes_.MergeFrom(from._impl_.axes_);
  _this->_impl_.buttons_.MergeFrom(from._impl_.buttons_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Joy::CopyFrom(const Joy& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dtproto.sensor_msgs.Joy)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Joy::IsInitialized() const {
  return true;
}

void Joy::InternalSwap(Joy* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.axes_.InternalSwap(&other->_impl_.axes_);
  _impl_.buttons_.InternalSwap(&other->_impl_.buttons_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Joy::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto_getter, &descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto_once,
      file_level_metadata_dtProto_2fsensor_5fmsgs_2fJoy_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace sensor_msgs
}  // namespace dtproto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dtproto::sensor_msgs::Joy*
Arena::CreateMaybeMessage< ::dtproto::sensor_msgs::Joy >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dtproto::sensor_msgs::Joy >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
