// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtProto/geometry_msgs/Wrench.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_dtProto_2fgeometry_5fmsgs_2fWrench_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_dtProto_2fgeometry_5fmsgs_2fWrench_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "dtProto/geometry_msgs/Point.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_dtProto_2fgeometry_5fmsgs_2fWrench_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_dtProto_2fgeometry_5fmsgs_2fWrench_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_dtProto_2fgeometry_5fmsgs_2fWrench_2eproto;
namespace dtproto {
namespace geometry_msgs {
class Wrench;
struct WrenchDefaultTypeInternal;
extern WrenchDefaultTypeInternal _Wrench_default_instance_;
}  // namespace geometry_msgs
}  // namespace dtproto
PROTOBUF_NAMESPACE_OPEN
template<> ::dtproto::geometry_msgs::Wrench* Arena::CreateMaybeMessage<::dtproto::geometry_msgs::Wrench>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace dtproto {
namespace geometry_msgs {

// ===================================================================

class Wrench final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:dtproto.geometry_msgs.Wrench) */ {
 public:
  inline Wrench() : Wrench(nullptr) {}
  ~Wrench() override;
  explicit PROTOBUF_CONSTEXPR Wrench(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Wrench(const Wrench& from);
  Wrench(Wrench&& from) noexcept
    : Wrench() {
    *this = ::std::move(from);
  }

  inline Wrench& operator=(const Wrench& from) {
    CopyFrom(from);
    return *this;
  }
  inline Wrench& operator=(Wrench&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Wrench& default_instance() {
    return *internal_default_instance();
  }
  static inline const Wrench* internal_default_instance() {
    return reinterpret_cast<const Wrench*>(
               &_Wrench_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Wrench& a, Wrench& b) {
    a.Swap(&b);
  }
  inline void Swap(Wrench* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Wrench* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Wrench* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Wrench>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Wrench& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Wrench& from) {
    Wrench::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Wrench* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "dtproto.geometry_msgs.Wrench";
  }
  protected:
  explicit Wrench(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kForceFieldNumber = 1,
    kTorqueFieldNumber = 2,
  };
  // .dtproto.geometry_msgs.Point3d force = 1;
  bool has_force() const;
  private:
  bool _internal_has_force() const;
  public:
  void clear_force();
  const ::dtproto::geometry_msgs::Point3d& force() const;
  PROTOBUF_NODISCARD ::dtproto::geometry_msgs::Point3d* release_force();
  ::dtproto::geometry_msgs::Point3d* mutable_force();
  void set_allocated_force(::dtproto::geometry_msgs::Point3d* force);
  private:
  const ::dtproto::geometry_msgs::Point3d& _internal_force() const;
  ::dtproto::geometry_msgs::Point3d* _internal_mutable_force();
  public:
  void unsafe_arena_set_allocated_force(
      ::dtproto::geometry_msgs::Point3d* force);
  ::dtproto::geometry_msgs::Point3d* unsafe_arena_release_force();

  // .dtproto.geometry_msgs.Point3d torque = 2;
  bool has_torque() const;
  private:
  bool _internal_has_torque() const;
  public:
  void clear_torque();
  const ::dtproto::geometry_msgs::Point3d& torque() const;
  PROTOBUF_NODISCARD ::dtproto::geometry_msgs::Point3d* release_torque();
  ::dtproto::geometry_msgs::Point3d* mutable_torque();
  void set_allocated_torque(::dtproto::geometry_msgs::Point3d* torque);
  private:
  const ::dtproto::geometry_msgs::Point3d& _internal_torque() const;
  ::dtproto::geometry_msgs::Point3d* _internal_mutable_torque();
  public:
  void unsafe_arena_set_allocated_torque(
      ::dtproto::geometry_msgs::Point3d* torque);
  ::dtproto::geometry_msgs::Point3d* unsafe_arena_release_torque();

  // @@protoc_insertion_point(class_scope:dtproto.geometry_msgs.Wrench)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::dtproto::geometry_msgs::Point3d* force_;
    ::dtproto::geometry_msgs::Point3d* torque_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_dtProto_2fgeometry_5fmsgs_2fWrench_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Wrench

// .dtproto.geometry_msgs.Point3d force = 1;
inline bool Wrench::_internal_has_force() const {
  return this != internal_default_instance() && _impl_.force_ != nullptr;
}
inline bool Wrench::has_force() const {
  return _internal_has_force();
}
inline const ::dtproto::geometry_msgs::Point3d& Wrench::_internal_force() const {
  const ::dtproto::geometry_msgs::Point3d* p = _impl_.force_;
  return p != nullptr ? *p : reinterpret_cast<const ::dtproto::geometry_msgs::Point3d&>(
      ::dtproto::geometry_msgs::_Point3d_default_instance_);
}
inline const ::dtproto::geometry_msgs::Point3d& Wrench::force() const {
  // @@protoc_insertion_point(field_get:dtproto.geometry_msgs.Wrench.force)
  return _internal_force();
}
inline void Wrench::unsafe_arena_set_allocated_force(
    ::dtproto::geometry_msgs::Point3d* force) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.force_);
  }
  _impl_.force_ = force;
  if (force) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dtproto.geometry_msgs.Wrench.force)
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::release_force() {
  
  ::dtproto::geometry_msgs::Point3d* temp = _impl_.force_;
  _impl_.force_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::unsafe_arena_release_force() {
  // @@protoc_insertion_point(field_release:dtproto.geometry_msgs.Wrench.force)
  
  ::dtproto::geometry_msgs::Point3d* temp = _impl_.force_;
  _impl_.force_ = nullptr;
  return temp;
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::_internal_mutable_force() {
  
  if (_impl_.force_ == nullptr) {
    auto* p = CreateMaybeMessage<::dtproto::geometry_msgs::Point3d>(GetArenaForAllocation());
    _impl_.force_ = p;
  }
  return _impl_.force_;
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::mutable_force() {
  ::dtproto::geometry_msgs::Point3d* _msg = _internal_mutable_force();
  // @@protoc_insertion_point(field_mutable:dtproto.geometry_msgs.Wrench.force)
  return _msg;
}
inline void Wrench::set_allocated_force(::dtproto::geometry_msgs::Point3d* force) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.force_);
  }
  if (force) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(force));
    if (message_arena != submessage_arena) {
      force = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, force, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.force_ = force;
  // @@protoc_insertion_point(field_set_allocated:dtproto.geometry_msgs.Wrench.force)
}

// .dtproto.geometry_msgs.Point3d torque = 2;
inline bool Wrench::_internal_has_torque() const {
  return this != internal_default_instance() && _impl_.torque_ != nullptr;
}
inline bool Wrench::has_torque() const {
  return _internal_has_torque();
}
inline const ::dtproto::geometry_msgs::Point3d& Wrench::_internal_torque() const {
  const ::dtproto::geometry_msgs::Point3d* p = _impl_.torque_;
  return p != nullptr ? *p : reinterpret_cast<const ::dtproto::geometry_msgs::Point3d&>(
      ::dtproto::geometry_msgs::_Point3d_default_instance_);
}
inline const ::dtproto::geometry_msgs::Point3d& Wrench::torque() const {
  // @@protoc_insertion_point(field_get:dtproto.geometry_msgs.Wrench.torque)
  return _internal_torque();
}
inline void Wrench::unsafe_arena_set_allocated_torque(
    ::dtproto::geometry_msgs::Point3d* torque) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.torque_);
  }
  _impl_.torque_ = torque;
  if (torque) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:dtproto.geometry_msgs.Wrench.torque)
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::release_torque() {
  
  ::dtproto::geometry_msgs::Point3d* temp = _impl_.torque_;
  _impl_.torque_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::unsafe_arena_release_torque() {
  // @@protoc_insertion_point(field_release:dtproto.geometry_msgs.Wrench.torque)
  
  ::dtproto::geometry_msgs::Point3d* temp = _impl_.torque_;
  _impl_.torque_ = nullptr;
  return temp;
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::_internal_mutable_torque() {
  
  if (_impl_.torque_ == nullptr) {
    auto* p = CreateMaybeMessage<::dtproto::geometry_msgs::Point3d>(GetArenaForAllocation());
    _impl_.torque_ = p;
  }
  return _impl_.torque_;
}
inline ::dtproto::geometry_msgs::Point3d* Wrench::mutable_torque() {
  ::dtproto::geometry_msgs::Point3d* _msg = _internal_mutable_torque();
  // @@protoc_insertion_point(field_mutable:dtproto.geometry_msgs.Wrench.torque)
  return _msg;
}
inline void Wrench::set_allocated_torque(::dtproto::geometry_msgs::Point3d* torque) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.torque_);
  }
  if (torque) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(torque));
    if (message_arena != submessage_arena) {
      torque = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, torque, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.torque_ = torque;
  // @@protoc_insertion_point(field_set_allocated:dtproto.geometry_msgs.Wrench.torque)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace geometry_msgs
}  // namespace dtproto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_dtProto_2fgeometry_5fmsgs_2fWrench_2eproto
