// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtProto/Service.proto

#include "dtProto/Service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dtproto {
}  // namespace dtproto
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_dtProto_2fService_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dtProto_2fService_2eproto = nullptr;
const uint32_t TableStruct_dtProto_2fService_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_dtProto_2fService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025dtProto/Service.proto\022\007dtproto\032\035dtProt"
  "o/std_msgs/Header.proto\032\034dtProto/std_msg"
  "s/State.proto\032\036dtProto/std_msgs/Request."
  "proto\032\"dtProto/robot_msgs/RobotInfo.prot"
  "o\032#dtProto/robot_msgs/ControlCmd.proto\032$"
  "dtProto/robot_msgs/MoveControl.proto\032%dt"
  "Proto/robot_msgs/JointControl.proto\032\035dtP"
  "roto/sensor_msgs/Joy.proto\032\033google/proto"
  "buf/empty.proto\032\036google/protobuf/wrapper"
  "s.proto2\370\003\n\tdtService\022\?\n\007Version\022\026.googl"
  "e.protobuf.Empty\032\034.google.protobuf.Strin"
  "gValue\022C\n\013StreamState\022\031.dtproto.std_msgs"
  ".Request\032\027.dtproto.std_msgs.State0\001\022C\n\004M"
  "ove\022\037.dtproto.robot_msgs.MoveControl\032\032.d"
  "tproto.std_msgs.Response\022I\n\tMoveJoint\022 ."
  "dtproto.robot_msgs.JointControl\032\032.dtprot"
  "o.std_msgs.Response\022E\n\007Command\022\036.dtproto"
  ".robot_msgs.ControlCmd\032\032.dtproto.std_msg"
  "s.Response\022E\n\tStreamJoy\022\030.dtproto.sensor"
  "_msgs.Joy\032\032.dtproto.std_msgs.Response(\0010"
  "\001\022G\n\016QueryRobotInfo\022\026.google.protobuf.Em"
  "pty\032\035.dtproto.robot_msgs.RobotInfob\006prot"
  "o3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_dtProto_2fService_2eproto_deps[10] = {
  &::descriptor_table_dtProto_2frobot_5fmsgs_2fControlCmd_2eproto,
  &::descriptor_table_dtProto_2frobot_5fmsgs_2fJointControl_2eproto,
  &::descriptor_table_dtProto_2frobot_5fmsgs_2fMoveControl_2eproto,
  &::descriptor_table_dtProto_2frobot_5fmsgs_2fRobotInfo_2eproto,
  &::descriptor_table_dtProto_2fsensor_5fmsgs_2fJoy_2eproto,
  &::descriptor_table_dtProto_2fstd_5fmsgs_2fHeader_2eproto,
  &::descriptor_table_dtProto_2fstd_5fmsgs_2fRequest_2eproto,
  &::descriptor_table_dtProto_2fstd_5fmsgs_2fState_2eproto,
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::_pbi::once_flag descriptor_table_dtProto_2fService_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dtProto_2fService_2eproto = {
    false, false, 882, descriptor_table_protodef_dtProto_2fService_2eproto,
    "dtProto/Service.proto",
    &descriptor_table_dtProto_2fService_2eproto_once, descriptor_table_dtProto_2fService_2eproto_deps, 10, 0,
    schemas, file_default_instances, TableStruct_dtProto_2fService_2eproto::offsets,
    nullptr, file_level_enum_descriptors_dtProto_2fService_2eproto,
    file_level_service_descriptors_dtProto_2fService_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dtProto_2fService_2eproto_getter() {
  return &descriptor_table_dtProto_2fService_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dtProto_2fService_2eproto(&descriptor_table_dtProto_2fService_2eproto);
namespace dtproto {

// @@protoc_insertion_point(namespace_scope)
}  // namespace dtproto
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
