// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtProto/robot_msgs/ArbitraryState.proto

#include "dtProto/robot_msgs/ArbitraryState.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace dtproto {
namespace robot_msgs {
PROTOBUF_CONSTEXPR ArbitraryStateTimeStamped::ArbitraryStateTimeStamped(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.header_)*/nullptr
  , /*decltype(_impl_.state_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ArbitraryStateTimeStampedDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ArbitraryStateTimeStampedDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ArbitraryStateTimeStampedDefaultTypeInternal() {}
  union {
    ArbitraryStateTimeStamped _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ArbitraryStateTimeStampedDefaultTypeInternal _ArbitraryStateTimeStamped_default_instance_;
}  // namespace robot_msgs
}  // namespace dtproto
static ::_pb::Metadata file_level_metadata_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto = nullptr;

const uint32_t TableStruct_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::dtproto::robot_msgs::ArbitraryStateTimeStamped, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::dtproto::robot_msgs::ArbitraryStateTimeStamped, _impl_.header_),
  PROTOBUF_FIELD_OFFSET(::dtproto::robot_msgs::ArbitraryStateTimeStamped, _impl_.state_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::dtproto::robot_msgs::ArbitraryStateTimeStamped)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::dtproto::robot_msgs::_ArbitraryStateTimeStamped_default_instance_._instance,
};

const char descriptor_table_protodef_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\'dtProto/robot_msgs/ArbitraryState.prot"
  "o\022\022dtproto.robot_msgs\032\035dtProto/std_msgs/"
  "Header.proto\032\"dtProto/std_msgs/PackedArr"
  "ay.proto\"t\n\031ArbitraryStateTimeStamped\022(\n"
  "\006header\030\001 \001(\0132\030.dtproto.std_msgs.Header\022"
  "-\n\005state\030\002 \001(\0132\036.dtproto.std_msgs.Packed"
  "Doubleb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto_deps[2] = {
  &::descriptor_table_dtProto_2fstd_5fmsgs_2fHeader_2eproto,
  &::descriptor_table_dtProto_2fstd_5fmsgs_2fPackedArray_2eproto,
};
static ::_pbi::once_flag descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto = {
    false, false, 254, descriptor_table_protodef_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto,
    "dtProto/robot_msgs/ArbitraryState.proto",
    &descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto_once, descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto_deps, 2, 1,
    schemas, file_default_instances, TableStruct_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto::offsets,
    file_level_metadata_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto, file_level_enum_descriptors_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto,
    file_level_service_descriptors_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto_getter() {
  return &descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto(&descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto);
namespace dtproto {
namespace robot_msgs {

// ===================================================================

class ArbitraryStateTimeStamped::_Internal {
 public:
  static const ::dtproto::std_msgs::Header& header(const ArbitraryStateTimeStamped* msg);
  static const ::dtproto::std_msgs::PackedDouble& state(const ArbitraryStateTimeStamped* msg);
};

const ::dtproto::std_msgs::Header&
ArbitraryStateTimeStamped::_Internal::header(const ArbitraryStateTimeStamped* msg) {
  return *msg->_impl_.header_;
}
const ::dtproto::std_msgs::PackedDouble&
ArbitraryStateTimeStamped::_Internal::state(const ArbitraryStateTimeStamped* msg) {
  return *msg->_impl_.state_;
}
void ArbitraryStateTimeStamped::clear_header() {
  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
}
void ArbitraryStateTimeStamped::clear_state() {
  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
}
ArbitraryStateTimeStamped::ArbitraryStateTimeStamped(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:dtproto.robot_msgs.ArbitraryStateTimeStamped)
}
ArbitraryStateTimeStamped::ArbitraryStateTimeStamped(const ArbitraryStateTimeStamped& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ArbitraryStateTimeStamped* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){nullptr}
    , decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_header()) {
    _this->_impl_.header_ = new ::dtproto::std_msgs::Header(*from._impl_.header_);
  }
  if (from._internal_has_state()) {
    _this->_impl_.state_ = new ::dtproto::std_msgs::PackedDouble(*from._impl_.state_);
  }
  // @@protoc_insertion_point(copy_constructor:dtproto.robot_msgs.ArbitraryStateTimeStamped)
}

inline void ArbitraryStateTimeStamped::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.header_){nullptr}
    , decltype(_impl_.state_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ArbitraryStateTimeStamped::~ArbitraryStateTimeStamped() {
  // @@protoc_insertion_point(destructor:dtproto.robot_msgs.ArbitraryStateTimeStamped)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ArbitraryStateTimeStamped::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.header_;
  if (this != internal_default_instance()) delete _impl_.state_;
}

void ArbitraryStateTimeStamped::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ArbitraryStateTimeStamped::Clear() {
// @@protoc_insertion_point(message_clear_start:dtproto.robot_msgs.ArbitraryStateTimeStamped)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.header_ != nullptr) {
    delete _impl_.header_;
  }
  _impl_.header_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.state_ != nullptr) {
    delete _impl_.state_;
  }
  _impl_.state_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ArbitraryStateTimeStamped::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .dtproto.std_msgs.Header header = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_header(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .dtproto.std_msgs.PackedDouble state = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_state(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ArbitraryStateTimeStamped::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:dtproto.robot_msgs.ArbitraryStateTimeStamped)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .dtproto.std_msgs.Header header = 1;
  if (this->_internal_has_header()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::header(this),
        _Internal::header(this).GetCachedSize(), target, stream);
  }

  // .dtproto.std_msgs.PackedDouble state = 2;
  if (this->_internal_has_state()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::state(this),
        _Internal::state(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dtproto.robot_msgs.ArbitraryStateTimeStamped)
  return target;
}

size_t ArbitraryStateTimeStamped::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dtproto.robot_msgs.ArbitraryStateTimeStamped)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .dtproto.std_msgs.Header header = 1;
  if (this->_internal_has_header()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.header_);
  }

  // .dtproto.std_msgs.PackedDouble state = 2;
  if (this->_internal_has_state()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.state_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ArbitraryStateTimeStamped::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ArbitraryStateTimeStamped::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ArbitraryStateTimeStamped::GetClassData() const { return &_class_data_; }


void ArbitraryStateTimeStamped::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ArbitraryStateTimeStamped*>(&to_msg);
  auto& from = static_cast<const ArbitraryStateTimeStamped&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:dtproto.robot_msgs.ArbitraryStateTimeStamped)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_header()) {
    _this->_internal_mutable_header()->::dtproto::std_msgs::Header::MergeFrom(
        from._internal_header());
  }
  if (from._internal_has_state()) {
    _this->_internal_mutable_state()->::dtproto::std_msgs::PackedDouble::MergeFrom(
        from._internal_state());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ArbitraryStateTimeStamped::CopyFrom(const ArbitraryStateTimeStamped& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dtproto.robot_msgs.ArbitraryStateTimeStamped)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ArbitraryStateTimeStamped::IsInitialized() const {
  return true;
}

void ArbitraryStateTimeStamped::InternalSwap(ArbitraryStateTimeStamped* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ArbitraryStateTimeStamped, _impl_.state_)
      + sizeof(ArbitraryStateTimeStamped::_impl_.state_)
      - PROTOBUF_FIELD_OFFSET(ArbitraryStateTimeStamped, _impl_.header_)>(
          reinterpret_cast<char*>(&_impl_.header_),
          reinterpret_cast<char*>(&other->_impl_.header_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ArbitraryStateTimeStamped::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto_getter, &descriptor_table_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto_once,
      file_level_metadata_dtProto_2frobot_5fmsgs_2fArbitraryState_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace robot_msgs
}  // namespace dtproto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::dtproto::robot_msgs::ArbitraryStateTimeStamped*
Arena::CreateMaybeMessage< ::dtproto::robot_msgs::ArbitraryStateTimeStamped >(Arena* arena) {
  return Arena::CreateMessageInternal< ::dtproto::robot_msgs::ArbitraryStateTimeStamped >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
